### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by akashpatil7** [deepsound-project/genre-recognition#5]
Getting this error during runtime..I have upgraded tensorflow to latest version (1.70). How do i get rid of this error?

**Comment by koz4k** [comment]
Should work with TensorFlow 1.9 as of #8.
